### ISSUE TITLE
Checkfiles problem - returns always Ok, never CRITICAL state

### ISSUE THREAD

**Issue by don27** [mickem/nscp#172]
Hi!

**My NSClient version: 0.4.3.143 2015-04-29**

I have an "interesting" problem:
I want to run the following nrpe command in order to find a file(s) in a specific path:
> /check_nrpe -n -H backserv -c checkfiles -a path="d:\\temp\\Backup\\1\\" pattern=*.tar filter="written > -8d" syntax="Backup files exist :%(name) size:%(size) bytes" MinWarn=0 MinCrit=0

**First case**: the specific file(s) exist, the command returns the following results (from nsclient log):
> D disk Created command: warn=count<=0 crit=count<=0 "filter=written > -8d" pattern=*.tar "detail-syntax=Backup files exist :%(name) size:%(size) bytes" top-syntax=${list} path=d:\temp\Backup\1\ empty-state=ok
> L cli OK: Backup files exist:filesize.tar size:24069 bytes
> L cli Performance data: 'count'=1;0;0

**Second case**: the requested file(s) doesn't exist, so the command should run to "CRITICAL" state and gives back the following detailed results (from nsclient log):**
> D disk Created command: warn=count<=0 crit=count<=0 "filter=written > -8d" pattern=*.tar "detail-syntax=Backup files exist :%(name) size:%(size) bytes" top-syntax=${list} path=d:\temp\Backup\1\ empty-state=ok
> L cli OK: No files found
> L cli Performance data: 'count'=0;0;0

**My question**: WHY??? Why "cli OK" and not "cli CRITICAL"? In my opinion that's very embarassing and irritating.

Can you help me? Any help or workaround appreciated!

Thnx in advance,
Don Lewis

**Comment by shivan** [comment]
Same problem here!
In 0.4.1.105 it worked.

**Comment by mickem** [comment]
Count is some what broken, will be fixed in 0.4.4

The problem is that the value which is checked is first 0 then 1 and then 2... so matching on < will never work.

**Comment by mickem** [comment]
This is fixed already (BTW) in the build of 0.4.4 which will be out in a bit...

**Comment by shivan** [comment]
Hi Mickem,

what means in a bit? The next days? Next month?

**Comment by mickem** [comment]
sorry, plan was late last night, but alas github was giving me attitude so hopefully it will work tonight when I get back home... so in maybe 8-10 hours?

**Comment by mickem** [comment]
The first release of 0.4.4. is out on github now https://github.com/mickem/nscp/releases/tag/0.4.4.2 PLEASE BEWARE this is the very very first alpha release of 0.4.4 so use with caution, a lot of testcases still fail...

**Comment by shivan** [comment]
Hi!
Does it really work? Using 0.4.4.2 I still get "No files found" and "OK".

That's my Check-Command:

```
object CheckCommand "check_last_backup_age" {
  import "plugin-check-command"

  command = [
    PluginDir + "/check_nrpe",
    "-H", "$address$",
    "-c", "CheckFiles",
    "-a",
    "path=$path$",
    "pattern=$pattern$",
    "MinCrit=0",
    "filter=$filter$",
    "syntax=Letztes Backup wurde am: %write% erstellt"
  ]
  vars = {
    "path" = "",
    "pattern" = "*.001",
    "filter" = "written gt -24h"
  }
}
```

Additionally I get now several errors on many other checks:
NSClient - ERROR: Invalid return from command: check_service
NSClient - ERROR: Invalid return from command: check_drivesize
NSClient - ERROR: Invalid return from command: check_cpu

But RAM Check for example ist working.

**Comment by box293** [comment]
Confirming that in 0.4.4.2 the problem still exists:

```
check_nrpe -H win2008r2-01 
I (0.4.4.2 2015-10-19) seem to be doing fine...

check_nrpe -H win2008r2-01 -c CheckFiles -a path='E:\\Transfinder\\TFdata\\Logs\\' pattern=TFX_*.* 'filter=written > -24h' 'master-syntax={%total% Files Found}' MinCrit=0

When files exist the output is (correct):
OK: All  files are ok|'count'=1;0;0
echo $?
0

When no files exist the output is (incorrect):
No files found|'count'=0;0;0
echo $?
0
```

**Comment by mickem** [comment]
I think this was fixed in 0.4.3

**Comment by mickem** [comment]
Pleas reopen if this is still an issue

**Comment by box293** [comment]
I believe this is still an issue. I tested with 0.4.4.15 and 0.5.0.17 and when "no files exist" (the check is to confirm they do) the exit code is  0.

This has all been with the legacy CheckFiles command.

I did notice that the output "No files found" seems to be related to the empty-syntax and empty-state which is specific to the newer check_files command.

With this in mind, using the newer check_files command seems to be the logical way to proceed. Based on this, I tested this command:
```
check_nrpe -H win2008r2-01 -c check_files -a path='E:\\Transfinder\\TFdata\Logs\\' pattern=TFX_*.* 'filter=written > -24h' 'critical=count<1' 'empty-state=critical'
No files found|'count'=0;0;1

echo $?
2
```
This command works fine with versions:
0.4.3.143
0.4.4.2
0.5.0.17

So to re-iterate, the problem exists in the legacy CheckFiles command.

**Comment by shivan** [comment]
Hi,

I can confirm. I tried 0.4.4.15. Problem still exists. I'm using legacy CheckFiles, too.

**Comment by mickem** [comment]
Hmm...

I cant seem to reproduce this.
The folder in question does not have any files in it.
0.4.4
```
mickem@felix:~$ /usr/lib/nagios/plugins/check_nrpe -H 192.168.0.201
I (0.4.4.21 2016-03-09) seem to be doing fine...
mickem@felix:~$ /usr/lib/nagios/plugins/check_nrpe -H 192.168.0.201 -c check_files -a path=c:/source/foo pattern=TFX_*.* "filter=written > -24h" "critical=count<1" "empty-state=critical"
No files found|'count'=0;0;1
mickem@felix:~$ echo $?
2
```

Same thing with 0.5.0
```
mickem@felix:~$ /usr/lib/nagios/plugins/check_nrpe -H 192.168.0.201
I (0.5.0.30 2016-03-13) seem to be doing fine...
mickem@felix:~$ /usr/lib/nagios/plugins/check_nrpe -H 192.168.0.201 -c check_files -a path=c:/source/foo pattern=TFX_*.* "filter=written > -24h" "critical=count<1" "empty-state=critical"
No files found|'count'=0;0;1
mickem@felix:~$ echo $?
2
```

**Comment by box293** [comment]
I just wanted to point out that that shivan is reporting an issue with CheckFiles and you and testing check_files. 

My comment was an example using check_files to suggest moving to the newer comman

**Comment by mickem** [comment]
Got it...

There is a change and some snags with the checkfiles command so I would advocate moving to check_file.
What I did in the above change was swap out "ok" for "unknown" when no files are found. This is as count is not considered when "no files are found", but hopefully this will make thins easier.
Swapping to the new command (as explained by @box293  will give you better control and what you expect)
