### ISSUE TITLE
[check_drivesize] Error: Failed to get size for: 1167: Le périphérique nest pas connecté.

### ISSUE THREAD

**Issue by garnier-quentin** [mickem/nscp#230]
Hi,

I have an issue with nsclient 0.4.3-143 on a Windows 2008 R2. I have tried to use 'ignore-unreadable' but it changes nothing (same error).
The log:

2015-12-16 16:34:21: error:D:\source\nscp\modules\CheckDisk\check_drive.cpp:432: Failed to get volume information \?\Volume{4ce0deb2-95bb-11e2-97ff-90b11c314e81}: 1167: Le périphérique n’est pas connecté.
2015-12-16 16:34:21: error:D:\source\nscp\modules\CheckDisk\check_drive.cpp:432: Failed to get volume information \?\Volume{36ac71dd-3148-11e3-9225-90b11c314e81}: 1167: Le périphérique n’est pas connecté. 

![screen](https://cloud.githubusercontent.com/assets/9079781/11953122/2120d6b4-a89e-11e5-928a-b832486ecab4.png)

Thanks. Ask me if you need to test a command to get information from the Windows.

**Comment by garnier-quentin** [comment]
Result of the command 'mountvol':



   \\?\Volume{1275271a-6684-11e2-8989-806e6f6e6963}\
       *** Aucun point de montage ***

   \\?\Volume{3c2e8c1b-6e7b-11e5-a295-90b11c314e81}\
       E:\

   \\?\Volume{4abad6a9-903b-11e2-9938-90b11c314e81}\
       D:\

   \\?\Volume{1275271b-6684-11e2-8989-806e6f6e6963}\
       C:\

   \\?\Volume{68108b69-881b-11e5-9dc7-90b11c314e81}\
       C:\Program Files\Microsoft System Center 2012\DPM\DPM\Volumes\Replica\No
n VSS Datasource Writer\vol_e97df4f6-4daf-4c0d-88b0-328921b08786\

   \\?\Volume{4ce0deac-95bb-11e2-97ff-90b11c314e81}\
       C:\Program Files\Microsoft System Center 2012\DPM\DPM\Volumes\DiffArea\S
qlServerWriter\vol_3a3c2565-e6aa-46a8-ac8e-50e8ea2d9473\

   \\?\Volume{68108b6f-881b-11e5-9dc7-90b11c314e81}\
       C:\Program Files\Microsoft System Center 2012\DPM\DPM\Volumes\DiffArea\N
on VSS Datasource Writer\vol_e97df4f6-4daf-4c0d-88b0-328921b08786\

   \\?\Volume{36ac71d7-3148-11e3-9225-90b11c314e81}\
       C:\Program Files\Microsoft System Center 2012\DPM\DPM\Volumes\DiffArea\N
on VSS Datasource Writer\vol_54759223-7ac7-48fe-91cf-7e1477f42455\

   \\?\Volume{4ce0deb2-95bb-11e2-97ff-90b11c314e81}\
       C:\Program Files\Microsoft System Center 2012\DPM\DPM\Volumes\Replica\Sq
lServerWriter\vol_3a3c2565-e6aa-46a8-ac8e-50e8ea2d9473\

   \\?\Volume{36ac71dd-3148-11e3-9225-90b11c314e81}\
       C:\Program Files\Microsoft System Center 2012\DPM\DPM\Volumes\Replica\No
n VSS Datasource Writer\vol_54759223-7ac7-48fe-91cf-7e1477f42455\

**Comment by mickem** [comment]
In 0.4.4 there is a "only mounted" option to check only drives which have an associated letter: http://docs.nsclient.org/reference/windows/CheckDisk.html#CheckDisk.check_drivesize.mounted

Maybe this would help?
You can also exclude but that is cumbersome right.

One other thought if it is a network drive you might wanna filter out remote drives?

**Comment by garnier-quentin** [comment]
Ok. We'll test with nsclient 0.4.4. But i want to check mount drives. I think you could add an option to not check disk with the error 'failed to get size'.

**Comment by mickem** [comment]
That's the intent of ignore unreadable (but possibly not the way it is implemented, I have fixed some issues related to this in 0.4.4 so might wanna try that and see if it works better)

**Comment by garnier-quentin** [comment]
Great. I'll test it with nsclient 0.4.4 and give you a feedback.

**Comment by garnier-quentin** [comment]
I have tested with NSClient 0.4.4-19 and still the same error. No change at all.

**Comment by mickem** [comment]
A few new options in the next 0.5.5. build which hopefully fixes this.

First off the default is to check mounted drives.
Secondly you can filter on readable status (which presumably should fix that)

**Comment by garnier-quentin** [comment]
Thanks. I'll give you a feedback soon!

**Comment by mickem** [comment]
https://github.com/mickem/nscp/releases/tag/0.5.0.32

**Comment by mickem** [comment]
Closing this, please reopen if you still have this issue...

**Comment by garnier-quentin** [comment]
Still the same problem with 0.5.0.35! Really weird.

If i use following filter: filter=readable = 1 and mounted = 1
It works 50% of times and other 50% i have the error of 'is not connected'.

If i use following filter: filter=mounted = 1
It never works.

If i use following filter:  filter=readable = 1
It works 50% of times and other 50% i have the error of 'is not connected'.

**Comment by mickem** [comment]
What does the NSClient++ log say?
Need the new file/line numbers so I can understand where the issue is...

**Comment by garnier-quentin** [comment]
The message:
```
2016-04-05 13:45:53: error:c:\source\master\modules\CheckDisk\check_drive.cpp:536: Failed to get volume information \\?\Volume{4ce0deb2-95bb-11e2-97ff-90b11c314e81}\: 1167: Le périphérique n’est pas connecté.


2016-04-05 13:45:53: error:c:\source\master\modules\CheckDisk\check_drive.cpp:536: Failed to get volume information \\?\Volume{36ac71dd-3148-11e3-9225-90b11c314e81}\: 1167: Le périphérique n’est pas connecté.
```

**Comment by garnier-quentin** [comment]
Sorry for the time. With nsclient 0.5.0.62, it's working with option: readable = 1 in the filter. Otherwise, i have the following error:
```
Filter processing failed: Failed to get size for \\?\Volume{4ce0deb2-95bb-11e2-97ff-90b11c314e81}\: 1167: Le périphérique nest pas connecté.
: C:\Program Files\Microsoft System Center 2012\DPM\DPM\Volumes\Replica\SqlServerWriter\vol_3a3c2565-e6aa-46a8-ac8e-50e8ea2d9473\ ? C:. and 0 < convert(1073741824) or C:\Program Files\Microsoft System Center 2012\DPM\DPM\Volumes\Replica\SqlServerWriter\vol_3a3c2565-e6aa-46a8-ac8e-50e8ea2d9473\ ? C:. and 0 < convert(2147483648)
```

**Comment by mickem** [comment]
Then I guess we can close this issue?

**Comment by garnier-quentin** [comment]
Yes you can :)
