### ISSUE TITLE
check_eventlog - Not Working?

### ISSUE THREAD

**Issue by selleryp** [mickem/nscp#500]
Hi,

Op5 support have suggested raising a ticket here, as another check_eventlog check does not appear to be flagging up an event in the event viewer.

I have the following configured -

$USER1$/check_nrpe -H $HOSTADDRESS$ -c check_eventlog -a file=Application "scan-range=-$ARG1$m" "filter=id = '$ARG2$' AND level = 'info'" AND keyword = 'Audit Failure'" "crit=count >= $ARG3$"

However, the output is showing 'no entires found', despite evidence of an Audit Failure event entry in the event viewer.

_USER1_/check_nrpe -H $HOSTADDRESS$ -c check_eventlog -a file=Application "scan-range=-120m" "filter=id = 18456 AND level = 'info' AND keyword like 'Audit Failure'" "crit=count >= 1"
Result code: 0
OK: No entries found|'count'=0;0;1 'problem_count'=0;0;0

There is an Event ID 18456 entry that matches these parameters (screenshot below) and is within the "scan-range=-120m".

![capture](https://user-images.githubusercontent.com/32900598/32606761-77d8347e-c54e-11e7-90ab-7031fb12cbeb.PNG)

Any ideas why the event is not being picked up?

We have added AND level = 'info', as this is not a warning/critica alert.

#488 was logged in relation to a similar issue with the Keywords module and this turned out to be a bug in the version of NSClient++, so not sure if it's a similar issue?
I have not tried upgrading to NSClient++ version: 0.5.2.14, as I assume that the bug was specific to the 'Microsoft-Windows-Security-Auditing' module/keywords.

Details -
NSClient++ version: 0.5.1045
OS and Version: Windows Server 2012 R2 Standard
Checking from: OP5
Checking with: check_eventlog

Thanks,
Paul

**Comment by mickem** [comment]
No, this was specific to `Audit Failure` and Success so presumably fixed here as well...

**Comment by selleryp** [comment]
Hi @mickem,

I have upgraded to NSClient++ version: 0.5.2.14 but the check is still not flagging up an event viewer entry that matches the parameters of the check:

$USER1$/check_nrpe -H $HOSTADDRESS$ -c check_eventlog -a file=Application "scan-range=-30m" "filter=id = '18456' AND level = 'info' AND keyword = 'Audit Failure'" "crit=count >= 1"

![capture2](https://user-images.githubusercontent.com/32900598/32717617-35d5422c-c852-11e7-84c5-1099dfe6b260.PNG)

Thanks,
Paul

**Comment by mickem** [comment]
What does give you:


```
check_eventlog file=Application "scan-range=-30m" "filter=id = 18456" show-all "detail-syntax=%(level), %(keyword)"
```

**Comment by selleryp** [comment]
It returns the following, so appears to work successfully:

$USER1$/check_nrpe -H $HOSTADDRESS$ -c check_eventlog file=Application "scan-range=-30m" "filter=id = 18456" show-all "detail-syntax=%(level), %(keyword)"

CRITICAL: 2 message(s) Application SnapManager for SQL Server (Failed to send email notification. Error Code 80131500 Description: Failure sending mail. Unable to connect to the remote server A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond IPADDRESS:25), Application SnapManager for SQL Server (Failed to send email notification. Error Code 80131500 Description: Failure sending mail. Unable to connect to the remote server A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond IPADDRESS:25)


I also tried again, replacing (level) with 'info' and (keyword) with 'Audit Failure' (in case this was what you were wanting me to do) and got the same output:

$USER1$/check_nrpe -H 10.146.0.200 -c check_eventlog file=Application "scan-range=-30m" "filter=id = 18456" show-all "detail-syntax=%(info), %(Audit Failure)"

CRITICAL: 2 message(s) Application SnapManager for SQL Server (Failed to send email notification. Error Code 80131500 Description: Failure sending mail. Unable to connect to the remote server A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond IPADDRESS:25), Application SnapManager for SQL Server (Failed to send email notification. Error Code 80131500 Description: Failure sending mail. Unable to connect to the remote server A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond IPADDRESS:25)

**Comment by mickem** [comment]
This cant be...

The top syntax should change the resulting output to return something akin to this:

```
information, win:EventlogClassic, information, win:EventlogClassic, information, win:EventlogClassic,
```

In other words the level and the keyword not the message

**Comment by op5-support** [comment]
Some tests from me:

`/opt/plugins/check_nrpe -s -H 172.27.86.50 -c check_eventlog -a file=Application "scan-range=-30m" "filter=id = 256" "detail-syntax=%(level), %(keyword)" "warn=none" "crit=none" show-all 
OK: 6 message(s) unknown, , unknown, , unknown, , unknown, , unknown, , unknown, 

/opt/plugins/check_nrpe -s -H 172.27.86.50 -c check_eventlog -a file=Application "scan-range=-30m" "filter=id = 9009" "detail-syntax=%(level), %(keyword)" "warn=none" "crit=none" show-all 
OK: 1 message(s) information, 

/opt/plugins/check_nrpe -s -H 172.27.86.50 -c check_eventlog -a file=System "scan-range=-30m" "filter=id = 7036" "detail-syntax=%(level), %(keyword)" "warn=none" "crit=none" show-all 
OK: 20 message(s) information, win:EventlogClassic, information, win:EventlogClassic, information, win:EventlogClassic, information, win:EventlogClassic, information, win:EventlogClassic, information, win:EventlogClassic, information, win:EventlogClassic, information, win:EventlogClassic, information, win:EventlogClassic, information, win:EventlogClassic, information, win:EventlogClassic, information, win:EventlogClassic, information, win:EventlogClassic, information, win:EventlogClassic, information, win:EventlogClassic, information, win:EventlogClassic, information, win:EventlogClassic, information, win:EventlogClassic, information, win:EventlogClassic, information, win:EventlogClassic  `

**Comment by selleryp** [comment]
OK, a slight tweak to include the -a and mine now shwos the following:

_USER1_/check_nrpe -H $HOSTADDRESS$ -c check_eventlog -a file=Application "scan-range=-30m" "filter=id = 18456" "detail-syntax=%(level), %(keyword)" "warn=none" "crit=none" show-all
Result code: 0
OK: 1 message(s) unknown, Audit Failure

**Comment by mickem** [comment]
Then should work:
```
check_eventlog -a file=Application "scan-range=-30m" "filter=id = '18456' AND keyword = 'Audit Failure'" "crit=count >= 1"
```


And the problem is the level not the keyword...

**Comment by selleryp** [comment]
Thanks mickem,
That is all working fine now.

**Comment by mickem** [comment]
Great, let me know if you face any other issues
