### ISSUE TITLE
check_memory with perf-config and show-all

### ISSUE THREAD

**Issue by Virsacer** [mickem/nscp#528]
### Issue and Steps to Reproduce

"perf-config" is not working with "check_memory" and when using "show-all" the "OK:" is missing.

```
/usr/lib/nagios/plugins/check_nrpe -H windows -c check_memory -a warn='used>80%' crit='used>90%' type=physical perf-config='physical %(ignored:true)' show-all
```

### Expected Behavior

OK: physical = 1.675GB|'physical'=1.6752GB;6.39959;7.19954;0;7.99949

### Actual Behavior

physical = 1.675GB|'physical'=1.6752GB;6.39959;7.19954;0;7.99949 'physical %'=21%;80;90;0;100

### Details

* NSClient++ version: 0.5.1.46
* OS and Version: Windows Server 2016
* Checking from: Icinga2
* Checking with: check_nrpe

### Additional Details

NSClient++ log:
```
2017-12-31 11:52:14: debug:c:\source\0.5.1\service\logger\nsclient_logger.cpp:52: Creating logger: threaded-file

```

**Comment by mickem** [comment]
The name of the performance metrics here is % so if you ignore that it works (at least for me).

```
check_memory "warn=used>80%" "crit=used>90%" type=physical "perf-config=%(ignored:true)" show-all
L        cli OK: physical = 11.637GB
L        cli  Performance data: 'physical'=11.63709GB;12.36326;13.90867;0;15.45407
```

Not sure about the OK I get an ok here, but I am using 0.5.2 so could be something which has been fixed?
Can you reproduce it with 0.5.2?

**Comment by Virsacer** [comment]
Thanks for your reply!
With "%" it is working as expected, but the "OK:" is still missing with 0.5.2.22
