### ISSUE TITLE
Web Server in 0.5.2.41

### ISSUE THREAD

**Issue by ArnoMLT** [mickem/nscp#576]
### Expected Behavior

Use the web interface !

### Actual Behavior

Since version 0.5.2.41 (and also all versions 0.5.3.x) I can't log in web server.
When I type in the good password, the navigator stays on the login page. No event logged. I checked with 'nscp web -- password --display' it's ok.
When I give a wrong password, I got "403 Invalid password" , and if I change the "allowed host" I got " 403 Your not allowed"

### Details

* NSClient++ version: 0.5.2.41 and 0.5.3.x
* OS and Version: Windows Server 2012
* Checking from: Centreon, Icinga, OP5, ...
* Checking with: check_nrpe, check_nt, ...

**Comment by dnsmichi** [comment]
I can confirm this behaviour, neither it works on localhost on Windows with Edge and Chrome (latest) nor on macOS with Safari, Chrome, Firefox (latest).

Seems the JS handler thinks that it is logged in, but the server does not.

**Comment by mintsoft** [comment]
#550 is also fixed in 5.2.35 @bmccorkle if that's an option for you

**Comment by mintsoft** [comment]
For the record, our nsclient only has these in with regards to IP's or password:
```
[/settings/default]

; ALLOWED HOSTS - A comaseparated list of allowed hosts. You can use netmasks (/ syntax) or * to create ranges.
allowed hosts = 192.168.0.16

[/settings/WEB/server]
password = ourpassword
```

**Comment by bmccorkle** [comment]
Any update on this?  I still can't login to the web interface

**Comment by mintsoft** [comment]
Just re-confirmed this with a fresh install of 5.2.41; it'll get fixed when @mickem picks up development again.

**Comment by bmccorkle** [comment]
I noticed there hadn't been any new releases in a while but I didn't see any news about @mickem stopping development.   Is this just a temporary pause?   I'm trying to roll out a new Icinga installation and planned on nsclient doing most of the work for windows hosts.

**Comment by mintsoft** [comment]
I have no idea specifically; however it's not too unusual for the project to have extended periods where no development occurs

**Comment by mickem** [comment]
I just wanted to assure everyone I am not dead :)

There are two reasons for no updates in a bit (well I moved this fall which meant I had less time to tinker as well) anyways: 
1. angular 2 is terrible (might have to switch that away) which made the new web ui not work very well...
2. currently upgrading dependencies like protobuf and such which have changed since the ancient version I was using before...

**Comment by bmccorkle** [comment]
Thanks for the update Michael.   I actually switched over to NRPEv3 with certificates and it's been working very well, so looks like I won't be trying to use the WebUI anytime soon.

**Comment by benrubson** [comment]
> Any update on this? I still can't login to the web interface

> I actually switched over to NRPEv3 with certificates and it's been working very well, so looks like I won't be trying to use the WebUI anytime soon.

Note that it does not prevent you from using the Rest API.
In addition configuration is rather simple :
```
[/settings/default]
allowed hosts = 127.0.0.1,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8
[/modules]
CheckSystem = enabled
WEBServer = enabled
[/settings/WEB/server/users/readuser]
password=MyPassw0rd
role=limited
[/settings/WEB/server/roles]
limited=*.get
```
Worth a try 👍
